/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BuyerId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactInfo = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const AgentProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'verified' : IDL.Bool,
  'contactInfo' : ContactInfo,
  'agency' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'rating' : IDL.Float64,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const BuyerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'contactInfo' : ContactInfo,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const PropertyStatus = IDL.Variant({
  'sold' : IDL.Null,
  'available' : IDL.Null,
  'draft' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'house' : IDL.Null,
  'land' : IDL.Null,
  'apartment' : IDL.Null,
});
export const AgentId = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'features' : IDL.Vec(IDL.Text),
  'country' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'area' : IDL.Float64,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'agentId' : AgentId,
  'updatedAt' : IDL.Int,
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Float64,
  'images' : IDL.Vec(ExternalBlob),
});
export const FilterCriteria = IDL.Record({
  'status' : IDL.Opt(PropertyStatus),
  'propertyType' : IDL.Opt(PropertyType),
  'city' : IDL.Opt(IDL.Text),
  'minBedrooms' : IDL.Opt(IDL.Nat),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'maxBedrooms' : IDL.Opt(IDL.Nat),
  'minPrice' : IDL.Opt(IDL.Float64),
});
export const InquiryStatus = IDL.Variant({
  'closed' : IDL.Null,
  'responded' : IDL.Null,
  'pending' : IDL.Null,
});
export const InquiryWithTitle = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'createdAt' : IDL.Int,
  'propertyTitle' : IDL.Text,
  'propertyId' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'message' : IDL.Text,
  'buyerId' : BuyerId,
  'response' : IDL.Opt(IDL.Text),
});
export const AgentReview = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'agentId' : IDL.Principal,
  'comment' : IDL.Text,
  'buyerId' : IDL.Principal,
  'rating' : IDL.Nat,
  'buyerName' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TicketMessage = IDL.Record({
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'senderPrincipal' : IDL.Principal,
  'senderLabel' : IDL.Text,
});
export const TicketPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'subject' : IDL.Text,
  'messages' : IDL.Vec(TicketMessage),
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'requesterEmail' : IDL.Text,
  'priority' : TicketPriority,
  'requesterPrincipal' : IDL.Principal,
});
export const TransactionStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'createdAt' : IDL.Int,
  'propertyTitle' : IDL.Text,
  'propertyId' : IDL.Nat,
  'sellerName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'currency' : IDL.Text,
  'buyerId' : IDL.Text,
  'sellerId' : IDL.Text,
  'buyerName' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'profileType' : IDL.Variant({
    'agent' : AgentProfile,
    'buyer' : BuyerProfile,
  }),
});
export const IdDocStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const IdDocumentSubmission = IDL.Record({
  'id' : IDL.Nat,
  'backBlob' : IDL.Opt(ExternalBlob),
  'status' : IdDocStatus,
  'submitterPrincipal' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'frontBlob' : ExternalBlob,
  'docType' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'propertyId' : IDL.Nat,
  'comment' : IDL.Text,
  'buyerId' : IDL.Principal,
  'rating' : IDL.Nat,
  'buyerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPropertyToFavorites' : IDL.Func([BuyerId, IDL.Nat], [], []),
  'approveIdDocument' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgentProfile' : IDL.Func([AgentProfile], [], []),
  'createBuyerProfile' : IDL.Func([BuyerProfile], [], []),
  'createProperty' : IDL.Func([Property], [IDL.Nat], []),
  'createSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'filterPublishedProperties' : IDL.Func(
      [FilterCriteria],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getAgentAverageRating' : IDL.Func([IDL.Principal], [IDL.Float64], ['query']),
  'getAgentInquiries' : IDL.Func([], [IDL.Vec(InquiryWithTitle)], ['query']),
  'getAgentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AgentProfile)],
      ['query'],
    ),
  'getAgentProperties' : IDL.Func([AgentId], [IDL.Vec(Property)], ['query']),
  'getAgentReviews' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AgentReview)],
      ['query'],
    ),
  'getAgentsForVerification' : IDL.Func([], [IDL.Vec(AgentProfile)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllPropertyImages' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
  'getAllPublishedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllSupportTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'agentCount' : IDL.Nat,
          'propertyCount' : IDL.Nat,
          'inquiryCount' : IDL.Nat,
          'buyerCount' : IDL.Nat,
          'userCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getBuyerInquiries' : IDL.Func([], [IDL.Vec(InquiryWithTitle)], ['query']),
  'getBuyerProfile' : IDL.Func([BuyerId], [IDL.Opt(BuyerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavoriteProperties' : IDL.Func([BuyerId], [IDL.Vec(Property)], ['query']),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getIdDocumentSubmissions' : IDL.Func(
      [],
      [IDL.Vec(IdDocumentSubmission)],
      ['query'],
    ),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getPropertyAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getPropertyDetails' : IDL.Func([IDL.Nat], [Property], ['query']),
  'getPropertyReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getPublishedProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getPublishedPropertyDetails' : IDL.Func([IDL.Nat], [Property], ['query']),
  'getTransactionsForBuyer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsForSeller' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSubmittedAgentReview' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'hasSubmittedReview' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'inquireProperty' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteProperty' : IDL.Func([IDL.Nat], [], []),
  'publishProperty' : IDL.Func([IDL.Nat], [], []),
  'rejectIdDocument' : IDL.Func([IDL.Nat], [], []),
  'removePropertyFromFavorites' : IDL.Func([BuyerId, IDL.Nat], [], []),
  'respondToInquiry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'respondToTicket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProperties' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
  'submitAgentReview' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'submitIdDocument' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
  'updateTicketPriority' : IDL.Func([IDL.Nat, TicketPriority], [], []),
  'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
  'updateTransactionStatus' : IDL.Func([IDL.Text, TransactionStatus], [], []),
  'uploadPropertyImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'verifyAgent' : IDL.Func([AgentId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BuyerId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactInfo = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AgentProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'verified' : IDL.Bool,
    'contactInfo' : ContactInfo,
    'agency' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'rating' : IDL.Float64,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const BuyerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'contactInfo' : ContactInfo,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const PropertyStatus = IDL.Variant({
    'sold' : IDL.Null,
    'available' : IDL.Null,
    'draft' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'house' : IDL.Null,
    'land' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const AgentId = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'features' : IDL.Vec(IDL.Text),
    'country' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'area' : IDL.Float64,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'agentId' : AgentId,
    'updatedAt' : IDL.Int,
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Float64,
    'images' : IDL.Vec(ExternalBlob),
  });
  const FilterCriteria = IDL.Record({
    'status' : IDL.Opt(PropertyStatus),
    'propertyType' : IDL.Opt(PropertyType),
    'city' : IDL.Opt(IDL.Text),
    'minBedrooms' : IDL.Opt(IDL.Nat),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'maxBedrooms' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Float64),
  });
  const InquiryStatus = IDL.Variant({
    'closed' : IDL.Null,
    'responded' : IDL.Null,
    'pending' : IDL.Null,
  });
  const InquiryWithTitle = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'createdAt' : IDL.Int,
    'propertyTitle' : IDL.Text,
    'propertyId' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'message' : IDL.Text,
    'buyerId' : BuyerId,
    'response' : IDL.Opt(IDL.Text),
  });
  const AgentReview = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'agentId' : IDL.Principal,
    'comment' : IDL.Text,
    'buyerId' : IDL.Principal,
    'rating' : IDL.Nat,
    'buyerName' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TicketMessage = IDL.Record({
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'senderPrincipal' : IDL.Principal,
    'senderLabel' : IDL.Text,
  });
  const TicketPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'messages' : IDL.Vec(TicketMessage),
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'requesterEmail' : IDL.Text,
    'priority' : TicketPriority,
    'requesterPrincipal' : IDL.Principal,
  });
  const TransactionStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'createdAt' : IDL.Int,
    'propertyTitle' : IDL.Text,
    'propertyId' : IDL.Nat,
    'sellerName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'currency' : IDL.Text,
    'buyerId' : IDL.Text,
    'sellerId' : IDL.Text,
    'buyerName' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'profileType' : IDL.Variant({
      'agent' : AgentProfile,
      'buyer' : BuyerProfile,
    }),
  });
  const IdDocStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const IdDocumentSubmission = IDL.Record({
    'id' : IDL.Nat,
    'backBlob' : IDL.Opt(ExternalBlob),
    'status' : IdDocStatus,
    'submitterPrincipal' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'frontBlob' : ExternalBlob,
    'docType' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'propertyId' : IDL.Nat,
    'comment' : IDL.Text,
    'buyerId' : IDL.Principal,
    'rating' : IDL.Nat,
    'buyerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPropertyToFavorites' : IDL.Func([BuyerId, IDL.Nat], [], []),
    'approveIdDocument' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgentProfile' : IDL.Func([AgentProfile], [], []),
    'createBuyerProfile' : IDL.Func([BuyerProfile], [], []),
    'createProperty' : IDL.Func([Property], [IDL.Nat], []),
    'createSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'filterPublishedProperties' : IDL.Func(
        [FilterCriteria],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getAgentAverageRating' : IDL.Func(
        [IDL.Principal],
        [IDL.Float64],
        ['query'],
      ),
    'getAgentInquiries' : IDL.Func([], [IDL.Vec(InquiryWithTitle)], ['query']),
    'getAgentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AgentProfile)],
        ['query'],
      ),
    'getAgentProperties' : IDL.Func([AgentId], [IDL.Vec(Property)], ['query']),
    'getAgentReviews' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AgentReview)],
        ['query'],
      ),
    'getAgentsForVerification' : IDL.Func(
        [],
        [IDL.Vec(AgentProfile)],
        ['query'],
      ),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllPropertyImages' : IDL.Func([], [IDL.Vec(ExternalBlob)], ['query']),
    'getAllPublishedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllSupportTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'agentCount' : IDL.Nat,
            'propertyCount' : IDL.Nat,
            'inquiryCount' : IDL.Nat,
            'buyerCount' : IDL.Nat,
            'userCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getBuyerInquiries' : IDL.Func([], [IDL.Vec(InquiryWithTitle)], ['query']),
    'getBuyerProfile' : IDL.Func([BuyerId], [IDL.Opt(BuyerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavoriteProperties' : IDL.Func(
        [BuyerId],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getIdDocumentSubmissions' : IDL.Func(
        [],
        [IDL.Vec(IdDocumentSubmission)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getPropertyAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getPropertyDetails' : IDL.Func([IDL.Nat], [Property], ['query']),
    'getPropertyReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getPublishedProperty' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Property)],
        ['query'],
      ),
    'getPublishedPropertyDetails' : IDL.Func([IDL.Nat], [Property], ['query']),
    'getTransactionsForBuyer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsForSeller' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSubmittedAgentReview' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'hasSubmittedReview' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'inquireProperty' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteProperty' : IDL.Func([IDL.Nat], [], []),
    'publishProperty' : IDL.Func([IDL.Nat], [], []),
    'rejectIdDocument' : IDL.Func([IDL.Nat], [], []),
    'removePropertyFromFavorites' : IDL.Func([BuyerId, IDL.Nat], [], []),
    'respondToInquiry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'respondToTicket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProperties' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
    'submitAgentReview' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'submitIdDocument' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
    'updateTicketPriority' : IDL.Func([IDL.Nat, TicketPriority], [], []),
    'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
    'updateTransactionStatus' : IDL.Func([IDL.Text, TransactionStatus], [], []),
    'uploadPropertyImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'verifyAgent' : IDL.Func([AgentId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };