/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgentId = Principal;
export interface AgentProfile {
  'bio' : string,
  'principal' : Principal,
  'verified' : boolean,
  'contactInfo' : ContactInfo,
  'agency' : string,
  'licenseNumber' : string,
  'rating' : number,
  'lastName' : string,
  'firstName' : string,
}
export interface AgentReview {
  'id' : bigint,
  'createdAt' : bigint,
  'agentId' : Principal,
  'comment' : string,
  'buyerId' : Principal,
  'rating' : bigint,
  'buyerName' : string,
  'transactionId' : string,
}
export type BuyerId = Principal;
export interface BuyerProfile {
  'principal' : Principal,
  'contactInfo' : ContactInfo,
  'lastName' : string,
  'firstName' : string,
}
export interface ContactInfo {
  'country' : string,
  'city' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface FilterCriteria {
  'status' : [] | [PropertyStatus],
  'propertyType' : [] | [PropertyType],
  'city' : [] | [string],
  'minBedrooms' : [] | [bigint],
  'maxPrice' : [] | [number],
  'maxBedrooms' : [] | [bigint],
  'minPrice' : [] | [number],
}
export type IdDocStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface IdDocumentSubmission {
  'id' : bigint,
  'backBlob' : [] | [ExternalBlob],
  'status' : IdDocStatus,
  'submitterPrincipal' : Principal,
  'submittedAt' : bigint,
  'email' : string,
  'frontBlob' : ExternalBlob,
  'docType' : string,
  'lastName' : string,
  'firstName' : string,
}
export type InquiryStatus = { 'closed' : null } |
  { 'responded' : null } |
  { 'pending' : null };
export interface InquiryWithTitle {
  'id' : bigint,
  'status' : InquiryStatus,
  'createdAt' : bigint,
  'propertyTitle' : string,
  'propertyId' : bigint,
  'updatedAt' : bigint,
  'message' : string,
  'buyerId' : BuyerId,
  'response' : [] | [string],
}
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'title' : string,
  'featured' : boolean,
  'features' : Array<string>,
  'country' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'area' : number,
  'city' : string,
  'createdAt' : bigint,
  'description' : string,
  'agentId' : AgentId,
  'updatedAt' : bigint,
  'currency' : string,
  'address' : string,
  'bathrooms' : bigint,
  'price' : number,
  'images' : Array<ExternalBlob>,
}
export type PropertyStatus = { 'sold' : null } |
  { 'available' : null } |
  { 'draft' : null };
export type PropertyType = { 'commercial' : null } |
  { 'house' : null } |
  { 'land' : null } |
  { 'apartment' : null };
export interface Review {
  'id' : bigint,
  'createdAt' : bigint,
  'propertyId' : bigint,
  'comment' : string,
  'buyerId' : Principal,
  'rating' : bigint,
  'buyerName' : string,
}
export interface Ticket {
  'id' : bigint,
  'status' : TicketStatus,
  'subject' : string,
  'messages' : Array<TicketMessage>,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'requesterEmail' : string,
  'priority' : TicketPriority,
  'requesterPrincipal' : Principal,
}
export interface TicketMessage {
  'createdAt' : bigint,
  'text' : string,
  'senderPrincipal' : Principal,
  'senderLabel' : string,
}
export type TicketPriority = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export type TicketStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'createdAt' : bigint,
  'propertyTitle' : string,
  'propertyId' : bigint,
  'sellerName' : string,
  'updatedAt' : bigint,
  'currency' : string,
  'buyerId' : string,
  'sellerId' : string,
  'buyerName' : string,
  'amount' : number,
}
export type TransactionStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface UserProfile {
  'profileType' : { 'agent' : AgentProfile } |
    { 'buyer' : BuyerProfile },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPropertyToFavorites' : ActorMethod<[BuyerId, bigint], undefined>,
  'approveIdDocument' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgentProfile' : ActorMethod<[AgentProfile], undefined>,
  'createBuyerProfile' : ActorMethod<[BuyerProfile], undefined>,
  'createProperty' : ActorMethod<[Property], bigint>,
  'createSupportTicket' : ActorMethod<[string, string, string], bigint>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'filterPublishedProperties' : ActorMethod<[FilterCriteria], Array<Property>>,
  'getAgentAverageRating' : ActorMethod<[Principal], number>,
  'getAgentInquiries' : ActorMethod<[], Array<InquiryWithTitle>>,
  'getAgentProfile' : ActorMethod<[Principal], [] | [AgentProfile]>,
  'getAgentProperties' : ActorMethod<[AgentId], Array<Property>>,
  'getAgentReviews' : ActorMethod<[Principal], Array<AgentReview>>,
  'getAgentsForVerification' : ActorMethod<[], Array<AgentProfile>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllPropertyImages' : ActorMethod<[], Array<ExternalBlob>>,
  'getAllPublishedProperties' : ActorMethod<[], Array<Property>>,
  'getAllSupportTickets' : ActorMethod<[], Array<Ticket>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'agentCount' : bigint,
      'propertyCount' : bigint,
      'inquiryCount' : bigint,
      'buyerCount' : bigint,
      'userCount' : bigint,
    }
  >,
  'getBuyerInquiries' : ActorMethod<[], Array<InquiryWithTitle>>,
  'getBuyerProfile' : ActorMethod<[BuyerId], [] | [BuyerProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavoriteProperties' : ActorMethod<[BuyerId], Array<Property>>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getIdDocumentSubmissions' : ActorMethod<[], Array<IdDocumentSubmission>>,
  'getProperty' : ActorMethod<[bigint], [] | [Property]>,
  'getPropertyAverageRating' : ActorMethod<[bigint], number>,
  'getPropertyDetails' : ActorMethod<[bigint], Property>,
  'getPropertyReviews' : ActorMethod<[bigint], Array<Review>>,
  'getPublishedProperty' : ActorMethod<[bigint], [] | [Property]>,
  'getPublishedPropertyDetails' : ActorMethod<[bigint], Property>,
  'getTransactionsForBuyer' : ActorMethod<[string], Array<Transaction>>,
  'getTransactionsForSeller' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasSubmittedAgentReview' : ActorMethod<[Principal], boolean>,
  'hasSubmittedReview' : ActorMethod<[bigint], boolean>,
  'inquireProperty' : ActorMethod<[bigint, string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteProperty' : ActorMethod<[bigint], undefined>,
  'publishProperty' : ActorMethod<[bigint], undefined>,
  'rejectIdDocument' : ActorMethod<[bigint], undefined>,
  'removePropertyFromFavorites' : ActorMethod<[BuyerId, bigint], undefined>,
  'respondToInquiry' : ActorMethod<[bigint, string], undefined>,
  'respondToTicket' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProperties' : ActorMethod<[string], Array<Property>>,
  'submitAgentReview' : ActorMethod<
    [Principal, string, bigint, string],
    undefined
  >,
  'submitIdDocument' : ActorMethod<
    [string, string, string, string, ExternalBlob, [] | [ExternalBlob]],
    bigint
  >,
  'submitReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'updateProperty' : ActorMethod<[bigint, Property], undefined>,
  'updateTicketPriority' : ActorMethod<[bigint, TicketPriority], undefined>,
  'updateTicketStatus' : ActorMethod<[bigint, TicketStatus], undefined>,
  'updateTransactionStatus' : ActorMethod<
    [string, TransactionStatus],
    undefined
  >,
  'uploadPropertyImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'verifyAgent' : ActorMethod<[AgentId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];