/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Review {
    id: bigint;
    createdAt: bigint;
    propertyId: bigint;
    comment: string;
    buyerId: Principal;
    rating: bigint;
    buyerName: string;
}
export interface UserProfile {
    profileType: {
        __kind__: "agent";
        agent: AgentProfile;
    } | {
        __kind__: "buyer";
        buyer: BuyerProfile;
    };
}
export interface IdDocumentSubmission {
    id: bigint;
    backBlob?: ExternalBlob;
    status: IdDocStatus;
    submitterPrincipal: Principal;
    submittedAt: bigint;
    email: string;
    frontBlob: ExternalBlob;
    docType: string;
    lastName: string;
    firstName: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface InquiryWithTitle {
    id: bigint;
    status: InquiryStatus;
    createdAt: bigint;
    propertyTitle: string;
    propertyId: bigint;
    updatedAt: bigint;
    message: string;
    buyerId: BuyerId;
    response?: string;
}
export interface FilterCriteria {
    status?: PropertyStatus;
    propertyType?: PropertyType;
    city?: string;
    minBedrooms?: bigint;
    maxPrice?: number;
    maxBedrooms?: bigint;
    minPrice?: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ContactInfo {
    country: string;
    city: string;
    email: string;
    address: string;
    phone: string;
}
export type BuyerId = Principal;
export interface Transaction {
    id: string;
    status: TransactionStatus;
    createdAt: bigint;
    propertyTitle: string;
    propertyId: bigint;
    sellerName: string;
    updatedAt: bigint;
    currency: string;
    buyerId: string;
    sellerId: string;
    buyerName: string;
    amount: number;
}
export interface BuyerProfile {
    principal: Principal;
    contactInfo: ContactInfo;
    lastName: string;
    firstName: string;
}
export interface Property {
    id: bigint;
    status: PropertyStatus;
    title: string;
    featured: boolean;
    features: Array<string>;
    country: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    area: number;
    city: string;
    createdAt: bigint;
    description: string;
    agentId: AgentId;
    updatedAt: bigint;
    currency: string;
    address: string;
    bathrooms: bigint;
    price: number;
    images: Array<ExternalBlob>;
}
export interface AgentReview {
    id: bigint;
    createdAt: bigint;
    agentId: Principal;
    comment: string;
    buyerId: Principal;
    rating: bigint;
    buyerName: string;
    transactionId: string;
}
export type AgentId = Principal;
export interface AgentProfile {
    bio: string;
    principal: Principal;
    verified: boolean;
    contactInfo: ContactInfo;
    agency: string;
    licenseNumber: string;
    rating: number;
    lastName: string;
    firstName: string;
}
export interface Ticket {
    id: bigint;
    status: TicketStatus;
    subject: string;
    messages: Array<TicketMessage>;
    createdAt: bigint;
    updatedAt: bigint;
    requesterEmail: string;
    priority: TicketPriority;
    requesterPrincipal: Principal;
}
export interface TicketMessage {
    createdAt: bigint;
    text: string;
    senderPrincipal: Principal;
    senderLabel: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum IdDocStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum InquiryStatus {
    closed = "closed",
    responded = "responded",
    pending = "pending"
}
export enum PropertyStatus {
    sold = "sold",
    available = "available",
    draft = "draft"
}
export enum PropertyType {
    commercial = "commercial",
    house = "house",
    land = "land",
    apartment = "apartment"
}
export enum TicketPriority {
    low = "low",
    high = "high",
    urgent = "urgent",
    medium = "medium"
}
export enum TicketStatus {
    resolved = "resolved",
    open = "open",
    inProgress = "inProgress"
}
export enum TransactionStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface NewsPost {
    id: bigint;
    title: string;
    summary: string;
    content: string;
    category: string;
    author: string;
    imageUrl: string;
    publishedAt: bigint;
    featured: boolean;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPropertyToFavorites(buyerId: BuyerId, propertyId: bigint): Promise<void>;
    approveIdDocument(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAgentProfile(profile: AgentProfile): Promise<void>;
    createBuyerProfile(profile: BuyerProfile): Promise<void>;
    createProperty(property: Property): Promise<bigint>;
    createSupportTicket(subject: string, message: string, email: string): Promise<bigint>;
    deleteProperty(propertyId: bigint): Promise<void>;
    filterPublishedProperties(criteria: FilterCriteria): Promise<Array<Property>>;
    getAgentAverageRating(agentId: Principal): Promise<number>;
    getAgentInquiries(): Promise<Array<InquiryWithTitle>>;
    getAgentProfile(agentPrincipal: Principal): Promise<AgentProfile | null>;
    getAgentProperties(agentId: AgentId): Promise<Array<Property>>;
    getAgentReviews(agentId: Principal): Promise<Array<AgentReview>>;
    getAgentsForVerification(): Promise<Array<AgentProfile>>;
    getAllProperties(): Promise<Array<Property>>;
    getAllPropertyImages(): Promise<Array<ExternalBlob>>;
    getAllPublishedProperties(): Promise<Array<Property>>;
    getAllSupportTickets(): Promise<Array<Ticket>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAnalytics(): Promise<{
        agentCount: bigint;
        propertyCount: bigint;
        inquiryCount: bigint;
        buyerCount: bigint;
        userCount: bigint;
    }>;
    getBuyerInquiries(): Promise<Array<InquiryWithTitle>>;
    getBuyerProfile(buyerId: BuyerId): Promise<BuyerProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavoriteProperties(buyerId: BuyerId): Promise<Array<Property>>;
    getFeaturedProperties(): Promise<Array<Property>>;
    getIdDocumentSubmissions(): Promise<Array<IdDocumentSubmission>>;
    getProperty(propertyId: bigint): Promise<Property | null>;
    getPropertyAverageRating(propertyId: bigint): Promise<number>;
    getPropertyDetails(propertyId: bigint): Promise<Property>;
    getPropertyReviews(propertyId: bigint): Promise<Array<Review>>;
    getPublishedProperty(propertyId: bigint): Promise<Property | null>;
    getPublishedPropertyDetails(propertyId: bigint): Promise<Property>;
    getTransactionsForBuyer(buyerId: string): Promise<Array<Transaction>>;
    getTransactionsForSeller(sellerId: string): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasSubmittedAgentReview(agentId: Principal): Promise<boolean>;
    hasSubmittedReview(propertyId: bigint): Promise<boolean>;
    inquireProperty(propertyId: bigint, message: string): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    promoteProperty(propertyId: bigint): Promise<void>;
    publishProperty(propertyId: bigint): Promise<void>;
    rejectIdDocument(id: bigint): Promise<void>;
    removePropertyFromFavorites(buyerId: BuyerId, propertyId: bigint): Promise<void>;
    respondToInquiry(inquiryId: bigint, response: string): Promise<void>;
    respondToTicket(ticketId: bigint, reply: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProperties(searchText: string): Promise<Array<Property>>;
    submitAgentReview(agentId: Principal, transactionId: string, rating: bigint, comment: string): Promise<void>;
    submitIdDocument(firstName: string, lastName: string, email: string, docType: string, frontBlob: ExternalBlob, backBlob: ExternalBlob | null): Promise<bigint>;
    submitReview(propertyId: bigint, rating: bigint, comment: string): Promise<void>;
    updateProperty(propertyId: bigint, updatedProperty: Property): Promise<void>;
    updateTicketPriority(ticketId: bigint, priority: TicketPriority): Promise<void>;
    updateTicketStatus(ticketId: bigint, status: TicketStatus): Promise<void>;
    updateTransactionStatus(id: string, status: TransactionStatus): Promise<void>;
    uploadPropertyImage(propertyId: bigint, blobId: ExternalBlob): Promise<void>;
    verifyAgent(agentId: AgentId): Promise<void>;
    createNewsPost(title: string, summary: string, content: string, category: string, author: string, imageUrl: string, featured: boolean): Promise<bigint>;
    getAllNewsPosts(): Promise<Array<NewsPost>>;
    getFeaturedNewsPosts(): Promise<Array<NewsPost>>;
    updateNewsPost(id: bigint, title: string, summary: string, content: string, category: string, author: string, imageUrl: string, featured: boolean): Promise<boolean>;
    deleteNewsPost(id: bigint): Promise<boolean>;
    getPublicMarketStats(): Promise<{ totalListings: bigint; totalAgents: bigint; totalBuyers: bigint }>;
}
import type { AgentId as _AgentId, AgentProfile as _AgentProfile, BuyerId as _BuyerId, BuyerProfile as _BuyerProfile, ExternalBlob as _ExternalBlob, FilterCriteria as _FilterCriteria, IdDocStatus as _IdDocStatus, IdDocumentSubmission as _IdDocumentSubmission, InquiryStatus as _InquiryStatus, InquiryWithTitle as _InquiryWithTitle, Property as _Property, PropertyStatus as _PropertyStatus, PropertyType as _PropertyType, Ticket as _Ticket, TicketMessage as _TicketMessage, TicketPriority as _TicketPriority, TicketStatus as _TicketStatus, Transaction as _Transaction, TransactionStatus as _TransactionStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPropertyToFavorites(arg0: BuyerId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPropertyToFavorites(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPropertyToFavorites(arg0, arg1);
            return result;
        }
    }
    async approveIdDocument(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveIdDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveIdDocument(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAgentProfile(arg0: AgentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgentProfile(arg0);
            return result;
        }
    }
    async createBuyerProfile(arg0: BuyerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuyerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuyerProfile(arg0);
            return result;
        }
    }
    async createProperty(arg0: Property): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProperty(await to_candid_Property_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProperty(await to_candid_Property_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSupportTicket(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupportTicket(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupportTicket(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async filterPublishedProperties(arg0: FilterCriteria): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPublishedProperties(to_candid_FilterCriteria_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPublishedProperties(to_candid_FilterCriteria_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentAverageRating(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentAverageRating(arg0);
            return result;
        }
    }
    async getAgentInquiries(): Promise<Array<InquiryWithTitle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentInquiries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentInquiries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentProfile(arg0: Principal): Promise<AgentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentProperties(arg0: AgentId): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentProperties(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentProperties(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentReviews(arg0: Principal): Promise<Array<AgentReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentReviews(arg0);
            return result;
        }
    }
    async getAgentsForVerification(): Promise<Array<AgentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentsForVerification();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentsForVerification();
            return result;
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPropertyImages(): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPropertyImages();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPropertyImages();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublishedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedProperties();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedProperties();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSupportTickets(): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupportTickets();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupportTickets();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<{
        agentCount: bigint;
        propertyCount: bigint;
        inquiryCount: bigint;
        buyerCount: bigint;
        userCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getBuyerInquiries(): Promise<Array<InquiryWithTitle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerInquiries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerInquiries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuyerProfile(arg0: BuyerId): Promise<BuyerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerProfile(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerProfile(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavoriteProperties(arg0: BuyerId): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoriteProperties(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoriteProperties(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProperties();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProperties();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIdDocumentSubmissions(): Promise<Array<IdDocumentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdDocumentSubmissions();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdDocumentSubmissions();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyAverageRating(arg0: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyAverageRating(arg0);
            return result;
        }
    }
    async getPropertyDetails(arg0: bigint): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyDetails(arg0);
                return from_candid_Property_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyDetails(arg0);
            return from_candid_Property_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyReviews(arg0);
            return result;
        }
    }
    async getPublishedProperty(arg0: bigint): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedProperty(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedProperty(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPropertyDetails(arg0: bigint): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPropertyDetails(arg0);
                return from_candid_Property_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPropertyDetails(arg0);
            return from_candid_Property_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsForBuyer(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsForBuyer(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsForBuyer(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsForSeller(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsForSeller(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsForSeller(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasSubmittedAgentReview(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSubmittedAgentReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSubmittedAgentReview(arg0);
            return result;
        }
    }
    async hasSubmittedReview(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSubmittedReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSubmittedReview(arg0);
            return result;
        }
    }
    async inquireProperty(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.inquireProperty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inquireProperty(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async promoteProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteProperty(arg0);
            return result;
        }
    }
    async publishProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishProperty(arg0);
            return result;
        }
    }
    async rejectIdDocument(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectIdDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectIdDocument(arg0);
            return result;
        }
    }
    async removePropertyFromFavorites(arg0: BuyerId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePropertyFromFavorites(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePropertyFromFavorites(arg0, arg1);
            return result;
        }
    }
    async respondToInquiry(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToInquiry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToInquiry(arg0, arg1);
            return result;
        }
    }
    async respondToTicket(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToTicket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToTicket(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProperties(arg0: string): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProperties(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProperties(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAgentReview(arg0: Principal, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAgentReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAgentReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitIdDocument(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob, arg5: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitIdDocument(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n65(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitIdDocument(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n65(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async submitReview(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProperty(arg0: bigint, arg1: Property): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, await to_candid_Property_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, await to_candid_Property_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTicketPriority(arg0: bigint, arg1: TicketPriority): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketPriority(arg0, to_candid_TicketPriority_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketPriority(arg0, to_candid_TicketPriority_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTicketStatus(arg0: bigint, arg1: TicketStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketStatus(arg0, to_candid_TicketStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketStatus(arg0, to_candid_TicketStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTransactionStatus(arg0: string, arg1: TransactionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransactionStatus(arg0, to_candid_TransactionStatus_n70(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransactionStatus(arg0, to_candid_TransactionStatus_n70(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadPropertyImage(arg0: bigint, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPropertyImage(arg0, await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPropertyImage(arg0, await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyAgent(arg0: AgentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAgent(arg0);
            return result;
        }
    }
    async createNewsPost(title: string, summary: string, content: string, category: string, author: string, imageUrl: string, featured: boolean): Promise<bigint> {
        const result = await this.actor.createNewsPost(title, summary, content, category, author, imageUrl, featured);
        return result as bigint;
    }
    async getAllNewsPosts(): Promise<Array<NewsPost>> {
        const result = await this.actor.getAllNewsPosts();
        return result as unknown as Array<NewsPost>;
    }
    async getFeaturedNewsPosts(): Promise<Array<NewsPost>> {
        const result = await this.actor.getFeaturedNewsPosts();
        return result as unknown as Array<NewsPost>;
    }
    async updateNewsPost(id: bigint, title: string, summary: string, content: string, category: string, author: string, imageUrl: string, featured: boolean): Promise<boolean> {
        const result = await this.actor.updateNewsPost(id, title, summary, content, category, author, imageUrl, featured);
        return result as unknown as boolean;
    }
    async deleteNewsPost(id: bigint): Promise<boolean> {
        const result = await this.actor.deleteNewsPost(id);
        return result as unknown as boolean;
    }
    async getPublicMarketStats(): Promise<{ totalListings: bigint; totalAgents: bigint; totalBuyers: bigint }> {
        const result = await this.actor.getPublicMarketStats();
        return result as unknown as { totalListings: bigint; totalAgents: bigint; totalBuyers: bigint };
    }
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IdDocStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdDocStatus): IdDocStatus {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
async function from_candid_IdDocumentSubmission_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdDocumentSubmission): Promise<IdDocumentSubmission> {
    return await from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryWithTitle_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryWithTitle): InquiryWithTitle {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyStatus): PropertyStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TicketPriority_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketPriority): TicketPriority {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AgentProfile]): AgentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BuyerProfile]): BuyerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n50(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Promise<Property | null> {
    return value.length === 0 ? null : await from_candid_Property_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PropertyStatus;
    title: string;
    featured: boolean;
    features: Array<string>;
    country: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    area: number;
    city: string;
    createdAt: bigint;
    description: string;
    agentId: _AgentId;
    updatedAt: bigint;
    currency: string;
    address: string;
    bathrooms: bigint;
    price: number;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    status: PropertyStatus;
    title: string;
    featured: boolean;
    features: Array<string>;
    country: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    area: number;
    city: string;
    createdAt: bigint;
    description: string;
    agentId: AgentId;
    updatedAt: bigint;
    currency: string;
    address: string;
    bathrooms: bigint;
    price: number;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_PropertyStatus_n23(_uploadFile, _downloadFile, value.status),
        title: value.title,
        featured: value.featured,
        features: value.features,
        country: value.country,
        propertyType: from_candid_PropertyType_n25(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        area: value.area,
        city: value.city,
        createdAt: value.createdAt,
        description: value.description,
        agentId: value.agentId,
        updatedAt: value.updatedAt,
        currency: value.currency,
        address: value.address,
        bathrooms: value.bathrooms,
        price: value.price,
        images: await from_candid_vec_n27(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InquiryStatus;
    createdAt: bigint;
    propertyTitle: string;
    propertyId: bigint;
    updatedAt: bigint;
    message: string;
    buyerId: _BuyerId;
    response: [] | [string];
}): {
    id: bigint;
    status: InquiryStatus;
    createdAt: bigint;
    propertyTitle: string;
    propertyId: bigint;
    updatedAt: bigint;
    message: string;
    buyerId: BuyerId;
    response?: string;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n32(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        propertyTitle: value.propertyTitle,
        propertyId: value.propertyId,
        updatedAt: value.updatedAt,
        message: value.message,
        buyerId: value.buyerId,
        response: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.response))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TicketStatus;
    subject: string;
    messages: Array<_TicketMessage>;
    createdAt: bigint;
    updatedAt: bigint;
    requesterEmail: string;
    priority: _TicketPriority;
    requesterPrincipal: Principal;
}): {
    id: bigint;
    status: TicketStatus;
    subject: string;
    messages: Array<TicketMessage>;
    createdAt: bigint;
    updatedAt: bigint;
    requesterEmail: string;
    priority: TicketPriority;
    requesterPrincipal: Principal;
} {
    return {
        id: value.id,
        status: from_candid_TicketStatus_n39(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        messages: value.messages,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        requesterEmail: value.requesterEmail,
        priority: from_candid_TicketPriority_n41(_uploadFile, _downloadFile, value.priority),
        requesterPrincipal: value.requesterPrincipal
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TransactionStatus;
    createdAt: bigint;
    propertyTitle: string;
    propertyId: bigint;
    sellerName: string;
    updatedAt: bigint;
    currency: string;
    buyerId: string;
    sellerId: string;
    buyerName: string;
    amount: number;
}): {
    id: string;
    status: TransactionStatus;
    createdAt: bigint;
    propertyTitle: string;
    propertyId: bigint;
    sellerName: string;
    updatedAt: bigint;
    currency: string;
    buyerId: string;
    sellerId: string;
    buyerName: string;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n46(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        propertyTitle: value.propertyTitle,
        propertyId: value.propertyId,
        sellerName: value.sellerName,
        updatedAt: value.updatedAt,
        currency: value.currency,
        buyerId: value.buyerId,
        sellerId: value.sellerId,
        buyerName: value.buyerName,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileType: {
        agent: _AgentProfile;
    } | {
        buyer: _BuyerProfile;
    };
}): {
    profileType: {
        __kind__: "agent";
        agent: AgentProfile;
    } | {
        __kind__: "buyer";
        buyer: BuyerProfile;
    };
} {
    return {
        profileType: from_candid_variant_n52(_uploadFile, _downloadFile, value.profileType)
    };
}
async function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    backBlob: [] | [_ExternalBlob];
    status: _IdDocStatus;
    submitterPrincipal: Principal;
    submittedAt: bigint;
    email: string;
    frontBlob: _ExternalBlob;
    docType: string;
    lastName: string;
    firstName: string;
}): Promise<{
    id: bigint;
    backBlob?: ExternalBlob;
    status: IdDocStatus;
    submitterPrincipal: Principal;
    submittedAt: bigint;
    email: string;
    frontBlob: ExternalBlob;
    docType: string;
    lastName: string;
    firstName: string;
}> {
    return {
        id: value.id,
        backBlob: record_opt_to_undefined(await from_candid_opt_n58(_uploadFile, _downloadFile, value.backBlob)),
        status: from_candid_IdDocStatus_n59(_uploadFile, _downloadFile, value.status),
        submitterPrincipal: value.submitterPrincipal,
        submittedAt: value.submittedAt,
        email: value.email,
        frontBlob: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.frontBlob),
        docType: value.docType,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    available: null;
} | {
    draft: null;
}): PropertyStatus {
    return "sold" in value ? PropertyStatus.sold : "available" in value ? PropertyStatus.available : "draft" in value ? PropertyStatus.draft : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    house: null;
} | {
    land: null;
} | {
    apartment: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "house" in value ? PropertyType.house : "land" in value ? PropertyType.land : "apartment" in value ? PropertyType.apartment : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    responded: null;
} | {
    pending: null;
}): InquiryStatus {
    return "closed" in value ? InquiryStatus.closed : "responded" in value ? InquiryStatus.responded : "pending" in value ? InquiryStatus.pending : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
}): TicketStatus {
    return "resolved" in value ? TicketStatus.resolved : "open" in value ? TicketStatus.open : "inProgress" in value ? TicketStatus.inProgress : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
}): TicketPriority {
    return "low" in value ? TicketPriority.low : "high" in value ? TicketPriority.high : "urgent" in value ? TicketPriority.urgent : "medium" in value ? TicketPriority.medium : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransactionStatus {
    return "cancelled" in value ? TransactionStatus.cancelled : "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    agent: _AgentProfile;
} | {
    buyer: _BuyerProfile;
}): {
    __kind__: "agent";
    agent: AgentProfile;
} | {
    __kind__: "buyer";
    buyer: BuyerProfile;
} {
    return "agent" in value ? {
        __kind__: "agent",
        agent: value.agent
    } : "buyer" in value ? {
        __kind__: "buyer",
        buyer: value.buyer
    } : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): IdDocStatus {
    return "pending" in value ? IdDocStatus.pending : "approved" in value ? IdDocStatus.approved : "rejected" in value ? IdDocStatus.rejected : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InquiryWithTitle>): Array<InquiryWithTitle> {
    return value.map((x)=>from_candid_InquiryWithTitle_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n44(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IdDocumentSubmission>): Promise<Array<IdDocumentSubmission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_IdDocumentSubmission_n56(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FilterCriteria_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilterCriteria): _FilterCriteria {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): _PropertyStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_Property_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Property): Promise<_Property> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TicketPriority_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketPriority): _TicketPriority {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): _TicketStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): _TransactionStatus {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: PropertyStatus;
    title: string;
    featured: boolean;
    features: Array<string>;
    country: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    area: number;
    city: string;
    createdAt: bigint;
    description: string;
    agentId: AgentId;
    updatedAt: bigint;
    currency: string;
    address: string;
    bathrooms: bigint;
    price: number;
    images: Array<ExternalBlob>;
}): Promise<{
    id: bigint;
    status: _PropertyStatus;
    title: string;
    featured: boolean;
    features: Array<string>;
    country: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    area: number;
    city: string;
    createdAt: bigint;
    description: string;
    agentId: _AgentId;
    updatedAt: bigint;
    currency: string;
    address: string;
    bathrooms: bigint;
    price: number;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        status: to_candid_PropertyStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        featured: value.featured,
        features: value.features,
        country: value.country,
        propertyType: to_candid_PropertyType_n14(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        area: value.area,
        city: value.city,
        createdAt: value.createdAt,
        description: value.description,
        agentId: value.agentId,
        updatedAt: value.updatedAt,
        currency: value.currency,
        address: value.address,
        bathrooms: value.bathrooms,
        price: value.price,
        images: await to_candid_vec_n16(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: PropertyStatus;
    propertyType?: PropertyType;
    city?: string;
    minBedrooms?: bigint;
    maxPrice?: number;
    maxBedrooms?: bigint;
    minPrice?: number;
}): {
    status: [] | [_PropertyStatus];
    propertyType: [] | [_PropertyType];
    city: [] | [string];
    minBedrooms: [] | [bigint];
    maxPrice: [] | [number];
    maxBedrooms: [] | [bigint];
    minPrice: [] | [number];
} {
    return {
        status: value.status ? candid_some(to_candid_PropertyStatus_n12(_uploadFile, _downloadFile, value.status)) : candid_none(),
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n14(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        minBedrooms: value.minBedrooms ? candid_some(value.minBedrooms) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        maxBedrooms: value.maxBedrooms ? candid_some(value.maxBedrooms) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileType: {
        __kind__: "agent";
        agent: AgentProfile;
    } | {
        __kind__: "buyer";
        buyer: BuyerProfile;
    };
}): {
    profileType: {
        agent: _AgentProfile;
    } | {
        buyer: _BuyerProfile;
    };
} {
    return {
        profileType: to_candid_variant_n64(_uploadFile, _downloadFile, value.profileType)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyStatus): {
    sold: null;
} | {
    available: null;
} | {
    draft: null;
} {
    return value == PropertyStatus.sold ? {
        sold: null
    } : value == PropertyStatus.available ? {
        available: null
    } : value == PropertyStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    house: null;
} | {
    land: null;
} | {
    apartment: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.house ? {
        house: null
    } : value == PropertyType.land ? {
        land: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "agent";
    agent: AgentProfile;
} | {
    __kind__: "buyer";
    buyer: BuyerProfile;
}): {
    agent: _AgentProfile;
} | {
    buyer: _BuyerProfile;
} {
    return value.__kind__ === "agent" ? {
        agent: value.agent
    } : value.__kind__ === "buyer" ? {
        buyer: value.buyer
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketPriority): {
    low: null;
} | {
    high: null;
} | {
    urgent: null;
} | {
    medium: null;
} {
    return value == TicketPriority.low ? {
        low: null
    } : value == TicketPriority.high ? {
        high: null
    } : value == TicketPriority.urgent ? {
        urgent: null
    } : value == TicketPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == TicketStatus.resolved ? {
        resolved: null
    } : value == TicketStatus.open ? {
        open: null
    } : value == TicketStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == TransactionStatus.cancelled ? {
        cancelled: null
    } : value == TransactionStatus.pending ? {
        pending: null
    } : value == TransactionStatus.completed ? {
        completed: null
    } : value == TransactionStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
